name: GH Respond
description: Responds to issue or PR comments

runs:
  using: composite
  steps:
    - name: Determine context type
      id: context
      shell: bash
      run: |
        EVENT=$(cat "$GITHUB_EVENT_PATH")
        IS_PR=$(echo "$EVENT" | jq -r '.issue.pull_request // empty')
        if [[ -n "$IS_PR" ]]; then
          echo "type=pr" >> $GITHUB_OUTPUT
        else
          echo "type=issue" >> $GITHUB_OUTPUT
        fi

    - uses: ./.github/actions/run-skill
      with:
        skill-name: gh-respond
        context-type: ${{ steps.context.outputs.type }}

    - uses: ./.github/actions/post-comment
      with:
        issue-number: ${{ github.event.issue.number }}
        repository: ${{ github.repository }}
        github-token: ${{ env.AGENTIC_BOT_TOKEN }}
