name: Dispatch
description: Takes github event data and runs the appropriate job

inputs:
  secrets-json:
    description: 'All secrets as JSON'
    required: true
  vars-json:
    description: 'All vars as JSON'
    required: false
    default: '{}'

runs:
  using: composite
  steps:
    - name: Inject environment
      uses: ./.github/actions/lib/inject-env
      with:
        secrets-json: ${{ inputs.secrets-json }}
        vars-json: ${{ inputs.vars-json }}

    - name: Route event
      id: route
      shell: bash
      run: |
        JOB=$($GITHUB_WORKSPACE/bin/determine-job-from-event)
        [[ -n "$JOB" ]] && echo "job=$JOB" >> $GITHUB_OUTPUT

    - name: Run gh-respond job
      uses: ./.github/actions/jobs/gh-respond
      if: steps.route.outputs.job == 'gh-respond'

    - name: Run pr-start job
      uses: ./.github/actions/jobs/pr-start
      if: steps.route.outputs.job == 'pr-start'

    - name: Run pr-fix job
      uses: ./.github/actions/jobs/pr-fix
      if: steps.route.outputs.job == 'pr-fix'

    - name: Run pr-merge job
      uses: ./.github/actions/jobs/pr-merge
      if: steps.route.outputs.job == 'pr-merge'
