name: PR Merge
description: Writes clean commit message and squash merges an approved PR

inputs:
  secrets-json:
    description: 'All secrets as JSON'
    required: true
  vars-json:
    description: 'All vars as JSON'
    required: false
    default: '{}'

runs:
  using: composite
  steps:
    - uses: chriswickett/agentic/.github/actions/run-skill@main
      with:
        skill-name: pr-merge
        context-type: pr
        fetch-depth: '0'
        secrets-json: ${{ inputs.secrets-json }}
        vars-json: ${{ inputs.vars-json }}

    - uses: chriswickett/agentic/.github/actions/squash-merge@main
      with:
        pr-number: ${{ github.event.pull_request.number }}
        repository: ${{ github.repository }}
        github-token: ${{ env.AGENTIC_BOT_TOKEN }}
