name: PR Fix
description: Fixes code based on PR review feedback

runs:
  using: composite
  steps:
    - name: Run skill
      uses: ./.github/actions/lib/run-skill
      with:
        skill-name: pr-fix
        context-type: pr
        fetch-depth: '0'

    - name: Commit and push
      uses: ./.github/actions/lib/git-commit-push
      with:
        repo-path: repo
        github-token: ${{ env.AGENTIC_BOT_TOKEN }}
        bot-name: ${{ env.AGENTIC_BOT_NAME }}
        bot-email: ${{ env.AGENTIC_BOT_EMAIL }}

    - name: Post comment
      uses: ./.github/actions/lib/post-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        repository: ${{ github.repository }}
        github-token: ${{ env.AGENTIC_BOT_TOKEN }}
