name: Setup Claude Agent
description: Sets up Claude CLI, skills repo, dependencies, mkcert, and Chrome DevTools MCP

runs:
  using: composite
  steps:
    - name: Clone skills repo
      shell: bash
      run: git clone https://github.com/chriswickett/agentic.git /tmp/skills

    - name: Install Claude CLI
      shell: bash
      run: npm install -g @anthropic-ai/claude-code

    - name: Install dependencies
      shell: bash
      run: |
        if [ -f "pnpm-lock.yaml" ]; then
          npm install -g pnpm
          pnpm install --frozen-lockfile
        elif [ -f "package-lock.json" ]; then
          npm ci
        elif [ -f "yarn.lock" ]; then
          npm install -g yarn
          yarn install --frozen-lockfile
        fi

    - name: Setup mkcert for trusted HTTPS
      shell: bash
      run: |
        curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
        chmod +x mkcert-v*-linux-amd64
        sudo mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert
        mkcert -install

    - name: Configure Chrome DevTools MCP
      shell: bash
      run: |
        echo '{"mcpServers":{"chrome-devtools":{"type":"stdio","command":"npx","args":["chrome-devtools-mcp@latest"]}}}' > ~/.claude.json
