name: GH Commented

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  gh-respond:
    if: |
     (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '@claude') && !startsWith(github.event.comment.body, '@claude /pr-start')) ||
     (github.event_name == 'issues' && startsWith(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: __AGENTIC_REPO__/.github/actions/setup-claude-agent@main

      - uses: __AGENTIC_REPO__/.github/actions/run-claude-skill@main
        with:
          skill-name: gh-respond
          context-type: issue
          context-number: ${{ github.event.issue.number }}
          repository: ${{ github.repository }}
          claude-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github-token: ${{ secrets.AGENTIC_BOT_TOKEN }}

      - uses: __AGENTIC_REPO__/.github/actions/post-comment@main
        with:
          comment-file: /tmp/comment.txt
          issue-or-pr-number: ${{ github.event.issue.number }}
          comment-type: issue
          repository: ${{ github.repository }}
          github-token: ${{ secrets.AGENTIC_BOT_TOKEN }}
